---
- name: Add PPAs
  apt_repository: repo={{ item }} state=present
  with_items:
    - ppa:keithw/mosh
    - ppa:klaus-vormweg/awesome
    - ppa:otto-kesselgulasch/gimp
    - ppa:videolan/stable-daily
    - ppa:lestcape/cinnamon

- name: Install graphical environments
  apt: name={{ item }} state=present
  with_items:
    - ubuntu-desktop
    - awesome
    - cinnamon
    - i3
    - xfce4
  notify:
    - lightdm

- name: Install editing suites
  apt: name={{ item }} state=present
  with_items:
    - gimp
    - gimp-data
    - gimp-data-extras
    - gimp-plugin-registry
    - inkscape
    - libreoffice
    - texlive
    - texmaker
    - texstudio

- name: Install programming tools
  apt: name={{ item }} state=present
  with_items:
    - build-essential
    - eclipse
    - git
    - openjdk-7-jdk
    - spim

- name: Install additional editors
  apt: name={{ item }} state=present
  with_items:
    - emacs
    - vim-gtk

- name: Install media playback programs
  apt: name={{ item }} state=present
  with_items:
    - mpv
    - vlc

- name: Install additional misc. programs
  apt: name={{ item }} state=present
  with_items:
    - firefox
    - gap
    - htop
    - keepass2
    - mlocate
    - mosh
    - redshift
    - rxvt-unicode-256color
    - sl
    - tcpdump
    - tmux
    - ubuntu-restricted-extras
    - wine
    - zsh

- include: greeter.yml

- name: Check to see if default awesome conf is already moved
  stat: path=/etc/xdg/awesome/rc.lua.default
  register: default_awesome

- name: Move awesome rc.lua to rc.lua.default
  command: mv /etc/xdg/awesome/rc.lua /etc/xdg/awesome/rc.lua.default
  when: default_awesome.stat.exists == False

- name: Check to see if default i3 conf is already moved
  stat: path=/etc/i3/config.default
  register: default_i3

- name: Move i3 config to config.default
  command: mv /etc/i3/config /etc/i3/config.default
  when: default_i3.stat.exists == False

- name: Copy over our non-friendly awesome config
  copy: src=awesome.conf dest=/etc/xdg/awesome/rc.lua owner=root group=root mode=0644

- name: Copy over our non-friendly i3 config
  copy: src=i3.conf dest=/etc/i3/config owner=root group=root mode=0644
