---
- name: Configure firewall
  copy: src=client.rules dest=/etc/iptables.d/client.rules owner=root group=root mode=0640
  notify:
  - iptables

- name: Add Google Chrome Signing Key
  apt_key: url=https://dl.google.com/linux/linux_signing_key.pub state=present

- name: Add PPAs
  apt_repository: repo={{ item }} state=present
  with_items:
    - ppa:keithw/mosh
    - ppa:klaus-vormweg/awesome
    - ppa:videolan/stable-daily
    - ppa:lestcape/cinnamon

- name: Add Google Chrome Repository
  apt_repository: repo='deb http://dl.google.com/linux/chrome/deb/ stable main' state=present

- name: Install graphical environments
  apt: name={{ item }} state=present
  with_items:
    - lubuntu-desktop
    - awesome
    - awesome-extra
    - i3
    - xfce4
  notify:
    - lightdm

- name: Install editing suites
  apt: name={{ item }} state=present
  with_items:
    - gimp
    - gimp-data
    - gimp-data-extras
    - gimp-plugin-registry
    - inkscape
    - libreoffice
    - texlive
    - texmaker
    - texstudio

- name: Install programming tools
  apt: name={{ item }} state=present
  with_items:
    - build-essential
    - eclipse
    - git
    - openjdk-7-jdk
    - spim

- name: Install additional editors
  apt: name={{ item }} state=present
  with_items:
    - emacs
    - vim-gtk

- name: Install media playback programs
  apt: name={{ item }} state=present
  with_items:
    - mpv
    - vlc

- name: Install additional misc. programs
  apt: name={{ item }} state=present
  with_items:
    - firefox
    - google-chrome-stable
    - gap
    - htop
    - keepass2
    - mlocate
    - mosh
    - redshift
    - rxvt-unicode-256color
    - shutter
    - sl
    - tcpdump
    - tmux
    - ubuntu-restricted-extras
    - wine
    - zsh

- name: Clobber Google-Chrome.list
  file: path=/etc/apt/sources.list.d/google-chrome.list state=absent

- name: Copy fix screens
  copy: src=fixScreens dest=/usr/local/bin/fixScreens owner=root group=root mode=0755

- include: greeter.yml

- name: Check to see if default awesome conf is already moved
  stat: path=/etc/xdg/awesome/rc.lua.default
  register: default_awesome

- name: Move awesome rc.lua to rc.lua.default
  command: mv /etc/xdg/awesome/rc.lua /etc/xdg/awesome/rc.lua.default
  when: default_awesome.stat.exists == False

- name: Check to see if default i3 conf is already moved
  stat: path=/etc/i3/config.default
  register: default_i3

- name: Move i3 config to config.default
  command: mv /etc/i3/config /etc/i3/config.default
  when: default_i3.stat.exists == False

- name: Copy over our non-friendly awesome config
  copy: src=awesome.conf dest=/etc/xdg/awesome/rc.lua owner=root group=root mode=0644

- name: Copy over our non-friendly i3 config
  copy: src=i3.conf dest=/etc/i3/config owner=root group=root mode=0644

- name: Disable Apport
  copy: src=apport.default dest=/etc/default/apport owner=root group=root mode=0644

- name: Disable update notifier autostart
  file: path=/etc/xdg/autostart/update-notifier.desktop state=absent

- name: Copy xdg autostarts
  copy: src={{ item }} dest=/etc/xdg/autostart/{{ item }} owner=root group=root mode=0644
  with_items:
    - xscreensaver.desktop
    - pc-client-linux.desktop

- name: Assures that app-default exists
  file: path=/usr/lib/X11/app-defaults state=directory

- name: Copy xscreensaver app-default config
  copy: src=XScreenSaver dest=/usr/lib/X11/app-defaults/XScreenSaver owner=root group=root mode=0644

- name: Copy xscreensaver default config
  copy: src=xscreensaver-config dest=/usr/share/lubuntu/xscreensaver/xscreensaver owner=root group=root mode=0644

- name: Copy grub default override
  copy: src=grub dest=/etc/default/grub owner=root group=root mode=0644
  notify:
    - grub

- name: Copy sudoers file
  copy: src=cv.sudoers dest=/etc/sudoers.d/cv owner=root group=root mode=0644

- name: Copy change-password
  copy: src=change_password.py dest=/usr/local/bin/change-password owner=root group=root mode=0555

- name: Copy change-password Desktop file
  copy: src=change-password.desktop dest=/usr/share/applications/change-password.desktop owner=root group=root mode=644

- name: Disable light-locker
  file: path=/etc/xdg/autostart/light-locker.desktop state=absent
