---
- name: Add PPAs
  apt_repository: repo={{ item }} state=present
  with_items:
    - ppa:keithw/mosh
    - ppa:klaus-vormweg/awesome
    - ppa:otto-kesselgulasch/gimp
    - ppa:videolan/stable-daily
    - ppa:lestcape/cinnamon

- name: Install graphical environments
  apt: name={{ item }} state=present
  with_items:
    - awesome
    - cinnamon
    - i3
    - xfce4
  notify:
    - lightdm

- name: Set default graphical shell
  copy: src=50-ubuntu.conf dest=/usr/share/lightdm/lightdm.conf.d/50-ubuntu.conf owner=root group=root mode=0644

- name: Install editing suites
  apt: name={{ item }} state=present
  with_items:
    - gimp
    - gimp-data
    - gimp-data-extras
    - gimp-plugin-registry
    - inkscape
    - libreoffice
    - texlive
    - texmaker
    - texstudio

- name: Install programming tools
  apt: name={{ item }} state=present
  with_items:
    - build-essential
    - eclipse
    - git
    - openjdk-7-jdk
    - spim

- name: Install additional editors
  apt: name={{ item }} state=present
  with_items:
    - emacs
    - vim-gtk

- name: Install media playback programs
  apt: name={{ item }} state=present
  with_items:
    - mpv
    - vlc

- name: Install additional misc. programs
  apt: name={{ item }} state=present
  with_items:
    - firefox
    - gap
    - htop
    - keepass2
    - mlocate
    - mosh
    - redshift
    - rxvt-unicode-256color
    - sl
    - tcpdump
    - tmux
    - ubuntu-restricted-extras
    - wine
    - zsh
